import React, { useState, useEffect } from 'react';
import { Save, AlertCircle, CheckCircle2, Loader2, FileEdit, BookOpen, Clock, Plus, Trash2, Shield, AlertTriangle } from 'lucide-react';
import { updateCourseSyllabus, fetchCoursesList, fetchAdminCoursesList, fetchInstructorDashboard } from '../../api';

interface SyllabusItem {
  chapter: string;
  title: string;
  description: string;
}

interface SyllabusEditorProps {
  courseId: string;
  initialSyllabus?: string;
  initialSyllabusContent?: string; // Fallback to handle alternate prop names gracefully
  onSyllabusSaved?: (newContent: string) => void;
}

export const SyllabusEditor: React.FC<SyllabusEditorProps> = ({
  courseId,
  initialSyllabus = '',
  initialSyllabusContent = '',
  onSyllabusSaved,
}) => {
  const incomingInitialContent = initialSyllabus || initialSyllabusContent || '';
  
  // Tab states: 'lessons' (structured chapters) or 'markdown' (full page syllabus markdown)
  const [activeTab, setActiveTab] = useState<'lessons' | 'markdown'>('lessons');
  
  // Data states
  const [syllabus, setSyllabus] = useState<string>(incomingInitialContent);
  const [lessons, setLessons] = useState<SyllabusItem[]>([]);
  
  // Syncing metadata states
  const [saving, setSaving] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<boolean>(false);
  const [lastUpdated, setLastUpdated] = useState<{ date: string; user: string } | null>(null);
  const [currentLastUpdatedAt, setCurrentLastUpdatedAt] = useState<string | null>(null);
  const [isConflict, setIsConflict] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  // Load course details (markdown + structured chapter list)
  const loadCourseData = async () => {
    try {
      let match: any = null;

      // 1. Fetch latest public courses list
      try {
        const listRes = await fetchCoursesList();
        if (listRes.success && listRes.courses) {
          match = listRes.courses.find(c => String(c.id) === String(courseId));
        }
      } catch (_) {}

      // 2. Fetch admin courses list if not found
      if (!match) {
        try {
          const adminRes = await fetchAdminCoursesList();
          if (adminRes.success && adminRes.courses) {
            match = adminRes.courses.find(c => String(c.id) === String(courseId));
          }
        } catch (_) {}
      }

      // 3. Fetch instructor courses list if still not found
      if (!match) {
        try {
          const instRes = await fetchInstructorDashboard();
          if (instRes.success && instRes.courses) {
            match = instRes.courses.find(c => String(c.id) === String(courseId));
          }
        } catch (_) {}
      }

      if (match) {
        // If markdown exists, use it. If not, auto-generate template from structured list
        if (match.syllabus_content) {
          setSyllabus(match.syllabus_content);
        } else if (match.syllabus && match.syllabus.length > 0) {
          const autoGeneratedMarkdown = `### ${match.title} - Complete Learning Path\n\n` +
            match.syllabus.map((item: any) => `#### ${item.chapter}: ${item.title}\n${item.description}`).join('\n\n');
          setSyllabus(autoGeneratedMarkdown);
        }
        
        if (match.syllabus) {
          const parsedSyllabus = typeof match.syllabus === 'string' ? JSON.parse(match.syllabus) : match.syllabus;
          setLessons(parsedSyllabus || []);
        }
      }
    } catch (err) {
      console.warn("Could not lazily pre-fill structured syllabus from lists:", err);
    }
  };

  // Fetch coordination audit details from the backend on load
  const loadCoordinationAudit = async () => {
    try {
      // 1. Try fetching admin list first
      try {
        const res = await fetchAdminCoursesList();
        if (res.success && res.courses) {
          const match = res.courses.find(c => String(c.id) === String(courseId));
          if (match) {
            if (match.syllabus_last_updated_at) {
              setCurrentLastUpdatedAt(match.syllabus_last_updated_at);
              setLastUpdated({
                date: match.syllabus_last_updated_at,
                user: match.syllabus_last_updated_by_name || 'System / Prior Version'
              });
            } else {
              setCurrentLastUpdatedAt(null);
              setLastUpdated(null);
            }
            return;
          }
        }
      } catch (_) {}

      // 2. Try fetching instructor dashboard list
      try {
        const res = await fetchInstructorDashboard();
        if (res.success && res.courses) {
          const match = res.courses.find(c => String(c.id) === String(courseId));
          if (match) {
            if (match.syllabus_last_updated_at) {
              setCurrentLastUpdatedAt(match.syllabus_last_updated_at);
              setLastUpdated({
                date: match.syllabus_last_updated_at,
                user: match.syllabus_last_updated_by_name || 'System / Prior Version'
              });
            } else {
              setCurrentLastUpdatedAt(null);
              setLastUpdated(null);
            }
            return;
          }
        }
      } catch (_) {}
    } catch (err: any) {
      console.warn("Failed retrieving course auditing coordinates:", err);
    }
  };

  useEffect(() => {
    loadCourseData();
    loadCoordinationAudit();
  }, [courseId]);

  // Handle saving both structured and markdown syllabus together
  const handleSaveSyllabus = async () => {
    setSaving(true);
    setError(null);
    setSuccess(false);
    setIsConflict(false);

    try {
      // Submit syllabus content and structural lessons matrix to backend
      const res = await updateCourseSyllabus(courseId, syllabus, currentLastUpdatedAt || undefined, lessons);
      if (res.success) {
        setSuccess(true);
        setIsConflict(false);
        
        // Update local coordination state immediately with the saved values
        if (res.syllabus_last_updated_at && res.syllabus_last_updated_by_name) {
          setLastUpdated({
            date: res.syllabus_last_updated_at,
            user: res.syllabus_last_updated_by_name
          });
          setCurrentLastUpdatedAt(res.syllabus_last_updated_at);
        } else {
          // Re-fetch coordination audit if they aren't directly returned
          await loadCoordinationAudit();
        }

        if (onSyllabusSaved) {
          onSyllabusSaved(syllabus);
        }
        
        // Reload all data to keep synced
        await loadCourseData();

        setTimeout(() => setSuccess(false), 4000);
      } else {
        setError(res.message || 'Error occurred while saving course syllabus.');
      }
    } catch (err: any) {
      if (err.status === 409 || err.code === 'CONCURRENCY_CONFLICT') {
        setIsConflict(true);
        setError("Conflict: Another user has updated this syllabus since you opened it. Please copy your recent changes to your clipboard, and refresh the page to sync the latest version.");
      } else {
        setError(err?.message || 'Failed connecting to server. Ensure you have proper instructor/admin credentials.');
      }
    } finally {
      setSaving(false);
    }
  };

  const loadSampleMarkdown = () => {
    const sample = `### Course Syllabus & Learning Path

#### Week 1: Foundations & Core Paradigms
- Introduction to architectural principles and foundational systems layout.
- Designing modular files, avoiding single-resource compilation bottlenecks.
- Hands-on Lab: Spinning up multi-stage SQLite relational setups.

#### Week 2: Routing Security & Auth Gates
- Restricting controllers using token validations and join checks.
- Building custom validation pipelines with Zod schemas.
- Hands-on Lab: Writing a course-ownership gate middleware.

#### Week 3: Interactive Visualizations & Exam Systems
- Implementing responsive d3 canvas elements.
- Constructing question pipelines (MCQs, True/False, Short answers).
- Final Project Submission & Peer Grading.`;
    setSyllabus(sample);
  };

  // Structured list helpers
  const handleAddLesson = () => {
    const nextChapterNumber = lessons.length + 1;
    setLessons([
      ...lessons,
      {
        chapter: `Lesson ${nextChapterNumber}`,
        title: `New Dynamic Subject ${nextChapterNumber}`,
        description: 'Introduce core concepts, structural syntax rules, and run local playground cell units.'
      }
    ]);
  };

  const handleRemoveLesson = (index: number) => {
    const updated = lessons.filter((_, i) => i !== index);
    // Relabel chapters sequentially to stay neat
    const sequential = updated.map((les, i) => ({
      ...les,
      chapter: `Lesson ${i + 1}`
    }));
    setLessons(sequential);
  };

  const handleLessonChange = (index: number, field: keyof SyllabusItem, value: string) => {
    const updated = [...lessons];
    updated[index] = {
      ...updated[index],
      [field]: value
    };
    setLessons(updated);
  };

  return (
    <div className="bg-white border border-gray-150 rounded-xl shadow-sm p-6 space-y-6 animate-fade-in" id="unified-syllabus-editor-container">
      
      {/* Coordination / Auditing UI Banner */}
      {lastUpdated ? (
        <div className="bg-indigo-50/70 border border-indigo-100 rounded-xl p-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-indigo-900 shadow-3xs" id="syllabus-audit-banner">
          <div className="flex items-center gap-2">
            <div className="h-7 w-7 rounded-lg bg-indigo-600/10 flex items-center justify-center text-indigo-700 shrink-0">
              <Clock className="w-4 h-4" />
            </div>
            <div>
              <span className="font-semibold block text-indigo-950">Syllabus Coordination Tracker</span>
              <span className="text-indigo-805 text-[11px]">
                Last updated on <span className="font-bold">{new Date(lastUpdated.date).toLocaleDateString('en-US', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short', year: 'numeric' })}</span> by <span className="font-bold text-indigo-950 font-sans">{lastUpdated.user}</span>
              </span>
            </div>
          </div>
          <span className="text-[9px] font-bold font-mono text-indigo-600 bg-indigo-100/80 px-2.5 py-1 rounded-md border border-indigo-200 uppercase tracking-wider select-none shrink-0 w-fit self-start sm:self-auto">
            Synced with Backend
          </span>
        </div>
      ) : (
        <div className="bg-slate-50 border border-gray-200/60 rounded-xl p-3.5 flex items-center gap-2 text-xs text-gray-400">
          <Clock className="w-4 h-4 italic text-gray-300" />
          <span>Syllabus coordination data not yet set. Save to publish your first tracked revision.</span>
        </div>
      )}

      {/* Primary Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-gray-100 pb-4">
        <div>
          <h3 className="text-md font-bold text-gray-900 flex items-center gap-1.5">
            <FileEdit className="w-5 h-5 text-indigo-600" />
            <span>Syllabus & Curriculum Editor</span>
          </h3>
          <p className="text-xs text-gray-550 mt-0.5">Define structured curriculum lectures and publish printable markdown syllabi for the student academy catalog.</p>
        </div>

        <div className="flex items-center gap-2" id="syllabus-tab-controls">
          <button
            type="button"
            onClick={() => setActiveTab('lessons')}
            className={`px-3.5 py-1.5 text-xs font-bold rounded-lg transition-all cursor-pointer ${
              activeTab === 'lessons'
                ? 'bg-indigo-600 text-white shadow-2xs'
                : 'bg-slate-50 border border-gray-200 text-slate-700 hover:bg-slate-100'
            }`}
          >
            Structured Lessons list
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('markdown')}
            className={`px-3.5 py-1.5 text-xs font-bold rounded-lg transition-all cursor-pointer ${
              activeTab === 'markdown'
                ? 'bg-indigo-600 text-white shadow-2xs'
                : 'bg-slate-50 border border-gray-200 text-slate-700 hover:bg-slate-100'
            }`}
          >
            Markdown Syllabus Document
          </button>
        </div>
      </div>

      {isConflict ? (
        <div className="p-5 bg-rose-50 border border-rose-200 rounded-xl space-y-4 shadow-3xs animate-fade-in" id="syllabus-conflict-banner">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-rose-600 rounded-lg text-white shrink-0">
              <AlertCircle className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <h4 className="text-sm font-bold text-rose-955">Warning: Someone else has modified this syllabus</h4>
              <p className="text-xs text-rose-900 leading-relaxed font-sans">
                Another instructor has updated this syllabus since you opened it. Please copy your recent changes to your clipboard, and refresh the page to sync the latest version.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 justify-end">
            <button
              type="button"
              onClick={() => {
                const textToCopy = activeTab === 'markdown' ? syllabus : JSON.stringify(lessons, null, 2);
                navigator.clipboard.writeText(textToCopy);
                setCopied(true);
                setTimeout(() => setCopied(false), 3000);
              }}
              className="px-4 py-2 border border-rose-300 text-rose-700 hover:bg-rose-100/50 hover:text-rose-800 text-xs font-bold rounded-lg transition-colors cursor-pointer"
            >
              {copied ? 'Copied to Clipboard! ✓' : 'Copy Changes to Clipboard'}
            </button>
            <button
              type="button"
              onClick={() => window.location.reload()}
              className="px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold rounded-lg transition-colors cursor-pointer shadow-3xs"
            >
              Refresh Page
            </button>
          </div>
        </div>
      ) : error ? (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-2 text-xs text-red-700 font-sans">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5 text-red-600" />
          <span>{error}</span>
        </div>
      ) : null}

      {success && (
        <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-lg flex items-start gap-2 text-xs text-emerald-850">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-emerald-950">Curriculum Published Successfully 🟢</p>
            <p className="text-gray-500 text-[11px] mt-0.5">The course profile description, structured chapter matrix, and markdown syllabus are synchronized. Students have immediate access.</p>
          </div>
        </div>
      )}

      {/* Tab Contents */}
      {activeTab === 'lessons' ? (
        <div className="space-y-4 animate-fade-in" id="structured-lessons-editor-layout">
          <div className="flex items-center justify-between bg-indigo-50/50 border border-indigo-100 px-4 py-3 rounded-xl">
            <div className="flex items-center gap-1.5 text-xs text-indigo-950">
              <Shield className="w-4 h-4 text-indigo-600" />
              <span>Configure Interactive Chapters shown on Student Dashboard Checklists</span>
            </div>
            <button
              type="button"
              onClick={handleAddLesson}
              className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-lg transition-all flex items-center gap-1 cursor-pointer select-none"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Add Syllabus Chapter</span>
            </button>
          </div>

          <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2" id="lessons-curriculum-list">
            {lessons.length === 0 ? (
              <div className="text-center py-12 bg-slate-50 border border-gray-150 rounded-xl space-y-2">
                <AlertTriangle className="w-8 h-8 text-amber-500 mx-auto" />
                <h4 className="text-xs font-bold text-gray-750">Curriculum Matrix is Empty</h4>
                <p className="text-[11px] text-gray-400">Initialize a chapter to construct interactive sandbox elements and test banks for students.</p>
              </div>
            ) : (
              lessons.map((lesson, idx) => (
                <div key={idx} className="bg-slate-50 border border-gray-200 rounded-xl p-4 space-y-3 relative group hover:border-indigo-200 transition-all">
                  <div className="flex items-center justify-between pb-1">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-[10px] bg-slate-200 border border-slate-300 text-slate-800 px-2 py-0.5 rounded font-black max-w-[80px]">
                        {lesson.chapter}
                      </span>
                      <span className="text-[10px] text-gray-400 font-mono">Index #{idx}</span>
                    </div>

                    <button
                      type="button"
                      onClick={() => handleRemoveLesson(idx)}
                      className="p-1 px-2.5 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 rounded-lg text-xs font-bold flex items-center gap-1 transition-all cursor-pointer select-none"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                      <span>Remove Chapter</span>
                    </button>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="md:col-span-1 space-y-1">
                      <label className="block text-[10px] font-bold font-mono tracking-wide text-gray-400 uppercase">Chapter Code Name</label>
                      <input
                        type="text"
                        required
                        value={lesson.chapter}
                        onChange={(e) => handleLessonChange(idx, 'chapter', e.target.value)}
                        className="w-full text-xs bg-white border border-gray-200 rounded-lg p-2 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
                        placeholder="e.g. Lesson 1"
                      />
                    </div>
                    <div className="md:col-span-3 space-y-1">
                      <label className="block text-[10px] font-bold font-mono tracking-wide text-gray-400 uppercase">Interactive Lesson Title</label>
                      <input
                        type="text"
                        required
                        value={lesson.title}
                        onChange={(e) => handleLessonChange(idx, 'title', e.target.value)}
                        className="w-full text-xs bg-white border border-gray-200 rounded-lg p-2 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
                        placeholder="e.g. Scaling Neural Architectures & Kernels with JAX"
                      />
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label className="block text-[10px] font-bold font-mono tracking-wide text-gray-400 uppercase">Detailed Chapter Objectives & Content Description</label>
                    <textarea
                      required
                      rows={2}
                      value={lesson.description}
                      onChange={(e) => handleLessonChange(idx, 'description', e.target.value)}
                      className="w-full text-xs bg-white border border-gray-200 rounded-lg p-2.5 focus:ring-1 focus:ring-indigo-500 focus:outline-none leading-relaxed"
                      placeholder="e.g. Explore basic functional programming with JAX and configure execution loops."
                    />
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      ) : (
        <div className="space-y-4 animate-fade-in" id="markdown-syllabus-editor-layout">
          <div className="flex items-center justify-between">
            <span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider font-mono">
              Curriculum Markdown Document
            </span>
            <button
              type="button"
              onClick={loadSampleMarkdown}
              className="px-2.5 py-1 text-[10px] border border-indigo-200 text-indigo-600 hover:bg-indigo-50 font-bold rounded-lg transition-colors cursor-pointer"
            >
              Insert Template Structure
            </button>
          </div>

          <textarea
            value={syllabus}
            onChange={(e) => setSyllabus(e.target.value)}
            placeholder="Type your course syllabus here (supports Markdown format)..."
            rows={14}
            className="w-full text-xs font-mono border border-gray-200 rounded-xl p-4 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 bg-slate-50/50 leading-relaxed"
          />
        </div>
      )}

      {/* Common Action Footer */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-50 border border-gray-150 p-4 rounded-xl">
        <div className="flex items-center gap-2 text-xs text-gray-550">
          <BookOpen className="w-4 h-4 text-gray-400 shrink-0" />
          <span>MountTech Unified Syllabus Manager: publishes both structured chapters and markdown document instantly.</span>
        </div>

        <button
          type="button"
          onClick={handleSaveSyllabus}
          disabled={saving}
          className="inline-flex items-center justify-center gap-1.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-bold text-xs px-5 py-2.5 rounded-lg transition-colors cursor-pointer shrink-0 select-none shadow-3xs"
        >
          {saving ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Save className="w-4 h-4" />
          )}
          <span>{saving ? 'Publishing Changes...' : 'Save Syllabus'}</span>
        </button>
      </div>
    </div>
  );
};
